name: news_app
description: News Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  webview_flutter: ^4.0.0
  cached_network_image: ^3.2.3
  google_mobile_ads: ^3.0.0
  contactus: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/